export type MonsterType =
    | "MONSTER_BOSS"
    | "MONSTER_ENV_ANIMAL"
    | "MONSTER_FISH"
    | "MONSTER_ORDINARY"
    | "MONSTER_PARTNER";

export type MonsterGrowCurveType =
    | "GROW_CURVE_NONE"
    | "GROW_CURVE_ACTIVITY_ATTACK_1"
    | "GROW_CURVE_ACTIVITY_ATTACK_2"
    | "GROW_CURVE_ACTIVITY_DEFENSE_2"
    | "GROW_CURVE_ACTIVITY_HP_1"
    | "GROW_CURVE_ACTIVITY_HP_2"
    | "GROW_CURVE_ATTACK"
    | "GROW_CURVE_ATTACK_2"
    | "GROW_CURVE_DEFENDING"
    | "GROW_CURVE_DEFENSE"
    | "GROW_CURVE_ELEMENT"
    | "GROW_CURVE_HP"
    | "GROW_CURVE_HP_2"
    | "GROW_CURVE_HP_ENVIRONMENT"
    | "GROW_CURVE_HP_LITTLEMONSTER"
    | "GROW_CURVE_KILL_EXP"
    | "GROW_CURVE_MATK"
    | "GROW_CURVE_MHP"
    | "GROW_CURVE_STRIKE"
    | "GROW_CURVE_STRIKE_HURT";

export type MonsterRarity =
    | "MONSTER_RARITY_BIG_BOSS_MONSTER"
    | "MONSTER_RARITY_BOSS_MONSTER"
    | "MONSTER_RARITY_ELITE_MONSTER"
    | "MONSTER_RARITY_SMALL_ENV_ANIMAL"
    | "MONSTER_RARITY_SMALL_MONSTER";

export type MonsterSecurityLevel = "BOSS" | "ELITE" | "NORMAL";

export type MonsterVisionLevel =
    | "VISION_LEVEL_LITTLE_REMOTE"
    | "VISION_LEVEL_NEARBY"
    | "VISION_LEVEL_NORMAL"
    | "VISION_LEVEL_REMOTE"
    | "VISION_LEVEL_SUPER"
    | "VISION_LEVEL_SUPER_NEARBY";
