export type ShopRefreshType =
    | "SHOP_REFRESH_NONE"
    | "SHOP_REFRESH_DAILY"
    | "SHOP_REFRESH_WEEKLY"
    | "SHOP_REFRESH_MONTHLY";

export type ShopOpenStateType =
    | "OPEN_STATE_NONE"
    | "OPEN_STATE_HOME"
    | "OPEN_STATE_SHOP_TYPE_BLACKSMITH"
    | "OPEN_STATE_SHOP_TYPE_CITY"
    | "OPEN_STATE_SHOP_TYPE_FOOD"
    | "OPEN_STATE_SHOP_TYPE_GENESISCRYSTAL"
    | "OPEN_STATE_SHOP_TYPE_GIFTPACKAGE"
    | "OPEN_STATE_SHOP_TYPE_GROCERY"
    | "OPEN_STATE_SHOP_TYPE_INAZUMA_SOUVENIR"
    | "OPEN_STATE_SHOP_TYPE_LIYUE_GROCERY"
    | "OPEN_STATE_SHOP_TYPE_LIYUE_RESTAURANT"
    | "OPEN_STATE_SHOP_TYPE_LIYUE_SOUVENIR"
    | "OPEN_STATE_SHOP_TYPE_NPC_TOMOKI"
    | "OPEN_STATE_SHOP_TYPE_PAIMON"
    | "OPEN_STATE_SHOP_TYPE_RECOMMANDED"
    | "OPEN_STATE_SHOP_TYPE_SEA_LAMP"
    | "OPEN_STATE_SHOP_TYPE_VIRTUAL_SHOP";

export type ShopType = `SHOP_TYPE_${string}`;

export type ShopPrecondition =
    | "SHOP_PRECONDITION_NONE"
    | "SHOP_PRECONDITION_ALCHEMY_SIM_LIMIT"
    | "SHOP_PRECONDITION_DONE_TEASURE_HUNT_V4_REGION"
    | "SHOP_PRECONDITION_GCG_LEVEL"
    | "SHOP_PRECONDITION_HISTORY_GOT_ANY_ITEM"
    | "SHOP_PRECONDITION_HISTORY_NEVER_GOT_ANY_ITEM"
    | "SHOP_PRECONDITION_HOME_LEVEL"
    | "SHOP_PRECONDITION_LAN_V6_REST"
    | "SHOP_PRECONDITION_QUEST_FINISH"
    | "SHOP_PRECONDITION_QUEST_FINISH_ANY"
    | "SHOP_PRECONDITION_QUEST_GLOBAL_VAR_EQUAL"
    | "SHOP_PRECONDITION_REST"
    | "SHOP_PRECONDITION_SHEET_FLEUR_FAIR_WATCHER_FINISH"
    | "SHOP_PRECONDITION_SHEET_REST"
    | "SHOP_PRECONDITION_SPECIFY";

export type ShopMaterialType =
    | "SHOP_TYPE_NONE"
    | "SHOP_TYPE_BEYOND_MCOIN"
    | "SHOP_TYPE_HCOIN"
    | "SHOP_TYPE_MCOIN";
