import type { ObfuscatedValue, TextMapHash } from '../common';
import type { FurnitureGroupRecordType, FurnitureSurfaceType, SpecialFurnitureType } from './common';

export type HomeWorldFurniture = {
    arrangeLimit: number;
    blockLegoText: boolean;
    canFloat: 0 | 1;
    comfort: number;
    cost: number;
    deployGlitchIndex: number;
    discountCost: number;
    dropable: boolean;
    editorClampDistance: number;
    effectIcon: string;
    floatIndicatorId: number;
    furnitureGadgetID: number[];
    furnType: number[];
    gadgetId: number;
    globalItemLimit: number;
    gridStyle: 0 | 1;
    groupRecordType: FurnitureGroupRecordType;
    height: number;
    icon: string;
    id: number;
    isSpecialFurniture: 0 | 1;
    itemIcon: string;
    itemType: "ITEM_FURNITURE";
    jsonName: string;
    pushTipsId: number;
    rank: number;
    rankLevel: number;
    roomSceneID: number;
    sourceTextList: number[];
    specialFurnitureType: SpecialFurnitureType;
    stackLimit: number;
    surfaceType: FurnitureSurfaceType;
    useLevel: number;
    weight: number;
} & ObfuscatedValue & Omit<TextMapHash, 'titleTextMapHash'>;
