import type { ObfuscatedValue } from './common';

export type Dungeon = {
    avatarLimitType: number;
    blockType: string;
    cityID: number;
    dayEnterCount: number;
    descTextMapHash: number;
    displayNameTextMapHash: number;
    enableQuestGuide: boolean;
    enterCostItems: {
        count: number;
        id: number;
    }[];
    entryPicPath: string;
    factorIcon: string;
    factorPic: string;
    failSettleCountdownTime: number;
    firstPassRewardPreviewID: number;
    forbiddenRestart: boolean;
    gearDescTextMapHash: number;
    id: number;
    involveType: string;
    isBanDieOptionReviveAfterSettle: boolean;
    isDungeonAllowSwitchTeam: number;
    isDynamicLevel: boolean;
    levelConfigMap: ObfuscatedValue;
    levelRevise: number;
    limitLevel: number;
    mpHideLevel: boolean;
    nameTextMapHash: number;
    passCond: number;
    passJumpDungeon: number;
    passRewardPreviewID: number;
    playType: string;
    previewMonsterList: number[];
    quitSettleCountdownTime: number;
    recommendElementTypes: string[];
    recommendTips: string[];
    reviveIntervalTime: number;
    reviveMaxCount: number;
    sceneId: number;
    serialId: number;
    settleCountdownTime: number;
    settleShows: string[];
    settleUIType: string;
    showLevel: number;
    slipOptimized: boolean;
    stateType: string;
    statueCostCount: number;
    statueCostID: number;
    statueDrop: number;
    subType: string;
    type: string;
} & ObfuscatedValue;
