import type { ObfuscatedValue } from './common';

export type HomeWorldFurniture = {
    arrangeLimit: number;
    blockLegoText: boolean;
    canFloat: number;
    comfort: number;
    cost: number;
    deployGlitchIndex: number;
    descTextMapHash: number;
    discountCost: number;
    dropable: boolean;
    editorClampDistance: number;
    effectIcon: string;
    floatIndicatorId: number;
    furnitureGadgetID: number[];
    furnType: number[];
    gadgetId: number;
    globalItemLimit: number;
    gridStyle: number;
    groupRecordType: string;
    height: number;
    icon: string;
    id: number;
    isSpecialFurniture: number;
    itemIcon: string;
    itemType: string;
    jsonName: string;
    nameTextMapHash: number;
    pushTipsId: number;
    rank: number;
    rankLevel: number;
    roomSceneID: number;
    sourceTextList: number[];
    specialFurnitureType: string;
    stackLimit: number;
    surfaceType: string;
    useLevel: number;
    weight: number;
} & ObfuscatedValue;
