import type { ObfuscatedValue } from './common';

export type Monster = {
    affix: number[];
    ai: string;
    attackBase: number;
    campID: number;
    canSwim: boolean;
    combatBGMLevel: number;
    combatConfigHash: number;
    controllerPathHash: number;
    controllerPathRemoteHash: number;
    critical: number;
    criticalHurt: number;
    defenseBase: number;
    deformationMeshPathHash: number;
    describeId: number;
    elecSubHurt: number;
    elementMastery: number;
    entityBudgetLevel: number;
    equips: number[];
    excludeWeathers: string;
    featureTagGroupID: number;
    fireSubHurt: number;
    grassSubHurt: number;
    hideNameInElementView: boolean;
    hpBase: number;
    hpDrops: {
        dropId: number;
        hpPercent: number;
    }[];
    iceSubHurt: number;
    id: number;
    isAIHashCheck: boolean;
    isInvisibleReset: boolean;
    killDropId: number;
    lodPatternName: string;
    monsterName: string;
    mpPropID: number;
    nameTextMapHash: number;
    physicalSubHurt: number;
    playType: string;
    prefabPathHash: number;
    prefabPathRagdollHash: number;
    prefabPathRemoteHash: number;
    propGrowCurves: {
        growCurve: string;
        type: string;
    }[];
    radarHintID: number;
    rockSubHurt: number;
    safetyCheck: boolean;
    scriptDataPathHash: number;
    securityLevel: string;
    serverScript: string;
    skin: string;
    type: string;
    visionLevel: string;
    waterSubHurt: number;
    windSubHurt: number;
} & ObfuscatedValue;
